<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-06 at 20:49:01.
 */

require_once 'Phactory/lib/Phactory.php';
require_once dirname(__FILE__) . '/../class.database.php';
require_once dirname(__FILE__) . '/../class.crud.php';

define('ENVIRONMENT', 'testing');

class CRUDTest extends PHPUnit_Framework_TestCase {
    /**
     * @var CRUD
     */
    protected $object;
    
    public static function setUpBeforeClass() {
	    $pdo = new PDO('mysql:host=127.0.0.1; dbname=crud_test', 'root', 'root');
        Phactory::setConnection($pdo);
        
        Phactory::reset();
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	    global $mysqli;
	    $mysqli = new Database('p:127.0.0.1', 'root', 'root', 'crud_test');
	    
        $this->object = new CRUD('test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }
    
    public static function tearDownAfterClass() {
        Phactory::reset();
    }

    /**
     * @covers CRUD::__get
     * @todo   Implement test__get().
     */
    public function test__get() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CRUD::display
     * @todo   Implement testDisplay().
     */
    public function testDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CRUD::display_date
     * @todo   Implement testDisplay_date().
     */
    public function testDisplay_date() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CRUD::__set
     * @todo   Implement test__set().
     */
    public function test__set() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CRUD::save
     * @todo   Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CRUD::create
     * @todo   Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CRUD::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers CRUD::delete
     * @todo   Implement testDelete().
     */
    public function testDelete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
